[[hooks]]
event = "SessionStart"
command = "WAITAGENT_AGENT_NAME=kimi 'D:\\TEMP\\waitagent-test\\waitagent-agent-signal-send.exe' 'SessionStart'"
timeout = 5
# waitagent-agent-signal:SessionStart

[[hooks]]
event = "UserPromptSubmit"
command = "WAITAGENT_AGENT_NAME=kimi 'D:\\TEMP\\waitagent-test\\waitagent-agent-signal-send.exe' 'UserPromptSubmit'"
timeout = 5
# waitagent-agent-signal:UserPromptSubmit

[[hooks]]
event = "PermissionRequest"
command = "WAITAGENT_AGENT_NAME=kimi 'D:\\TEMP\\waitagent-test\\waitagent-agent-signal-send.exe' 'PermissionRequest'"
timeout = 5
# waitagent-agent-signal:PermissionRequest

[[hooks]]
event = "PermissionResult"
command = "WAITAGENT_AGENT_NAME=kimi 'D:\\TEMP\\waitagent-test\\waitagent-agent-signal-send.exe' 'PermissionResult'"
timeout = 5
# waitagent-agent-signal:PermissionResult

[[hooks]]
event = "PreToolUse"
command = "WAITAGENT_AGENT_NAME=kimi 'D:\\TEMP\\waitagent-test\\waitagent-agent-signal-send.exe' 'PreToolUse'"
timeout = 5
# waitagent-agent-signal:PreToolUse

[[hooks]]
event = "PostToolUse"
command = "WAITAGENT_AGENT_NAME=kimi 'D:\\TEMP\\waitagent-test\\waitagent-agent-signal-send.exe' 'PostToolUse'"
timeout = 5
# waitagent-agent-signal:PostToolUse

[[hooks]]
event = "PostToolUseFailure"
command = "WAITAGENT_AGENT_NAME=kimi 'D:\\TEMP\\waitagent-test\\waitagent-agent-signal-send.exe' 'PostToolUseFailure'"
timeout = 5
# waitagent-agent-signal:PostToolUseFailure

[[hooks]]
event = "Stop"
command = "WAITAGENT_AGENT_NAME=kimi 'D:\\TEMP\\waitagent-test\\waitagent-agent-signal-send.exe' 'Stop'"
timeout = 5
# waitagent-agent-signal:Stop

[[hooks]]
event = "StopFailure"
command = "WAITAGENT_AGENT_NAME=kimi 'D:\\TEMP\\waitagent-test\\waitagent-agent-signal-send.exe' 'StopFailure'"
timeout = 5
# waitagent-agent-signal:StopFailure

[[hooks]]
event = "Interrupt"
command = "WAITAGENT_AGENT_NAME=kimi 'D:\\TEMP\\waitagent-test\\waitagent-agent-signal-send.exe' 'Interrupt'"
timeout = 5
# waitagent-agent-signal:Interrupt

[[hooks]]
event = "SessionEnd"
command = "WAITAGENT_AGENT_NAME=kimi 'D:\\TEMP\\waitagent-test\\waitagent-agent-signal-send.exe' 'SessionEnd'"
timeout = 5
# waitagent-agent-signal:SessionEnd

